/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MemberUpdatesCard: typeof import('./src/components/dashboard/MemberUpdatesCard.vue')['default']
    PositionsCard: typeof import('./src/components/dashboard/PositionsCard.vue')['default']
    ProfileCard: typeof import('./src/components/dashboard/ProfileCard.vue')['default']
    RackspaceEmailCard: typeof import('./src/components/dashboard/RackspaceEmailCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WelcomeCard: typeof import('./src/components/dashboard/WelcomeCard.vue')['default']
  }
}
