/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'analytics': RouteRecordInfo<'analytics', '/analytics', Record<never, never>, Record<never, never>>,
    'committees': RouteRecordInfo<'committees', '/committees', Record<never, never>, Record<never, never>>,
    'db-explorer': RouteRecordInfo<'db-explorer', '/db-explorer', Record<never, never>, Record<never, never>>,
    'events': RouteRecordInfo<'events', '/events', Record<never, never>, Record<never, never>>,
    'events-atx': RouteRecordInfo<'events-atx', '/events/atx', Record<never, never>, Record<never, never>>,
    'events-cfs': RouteRecordInfo<'events-cfs', '/events/cfs', Record<never, never>, Record<never, never>>,
    'events-convention': RouteRecordInfo<'events-convention', '/events/convention', Record<never, never>, Record<never, never>>,
    'events-niw': RouteRecordInfo<'events-niw', '/events/niw', Record<never, never>, Record<never, never>>,
    'facilities': RouteRecordInfo<'facilities', '/facilities', Record<never, never>, Record<never, never>>,
    'infrastructure': RouteRecordInfo<'infrastructure', '/infrastructure', Record<never, never>, Record<never, never>>,
    'legislative': RouteRecordInfo<'legislative', '/legislative', Record<never, never>, Record<never, never>>,
    'legislative-house': RouteRecordInfo<'legislative-house', '/legislative/house', Record<never, never>, Record<never, never>>,
    'legislative-pac': RouteRecordInfo<'legislative-pac', '/legislative/pac', Record<never, never>, Record<never, never>>,
    'legislative-resources': RouteRecordInfo<'legislative-resources', '/legislative/resources', Record<never, never>, Record<never, never>>,
    'legislative-senate': RouteRecordInfo<'legislative-senate', '/legislative/senate', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'ncept': RouteRecordInfo<'ncept', '/ncept', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'regions': RouteRecordInfo<'regions', '/regions', Record<never, never>, Record<never, never>>,
    'resources': RouteRecordInfo<'resources', '/resources', Record<never, never>, Record<never, never>>,
    'resources-constitution': RouteRecordInfo<'resources-constitution', '/resources/constitution', Record<never, never>, Record<never, never>>,
    'resources-contracts': RouteRecordInfo<'resources-contracts', '/resources/contracts', Record<never, never>, Record<never, never>>,
    'resources-docs': RouteRecordInfo<'resources-docs', '/resources/docs', Record<never, never>, Record<never, never>>,
    'resources-neb-minutes': RouteRecordInfo<'resources-neb-minutes', '/resources/neb-minutes', Record<never, never>, Record<never, never>>,
    'resources-newsletters': RouteRecordInfo<'resources-newsletters', '/resources/newsletters', Record<never, never>, Record<never, never>>,
    'safety': RouteRecordInfo<'safety', '/safety', Record<never, never>, Record<never, never>>,
    'safety-articles': RouteRecordInfo<'safety-articles', '/safety/articles', Record<never, never>, Record<never, never>>,
    'safety-programs': RouteRecordInfo<'safety-programs', '/safety/programs', Record<never, never>, Record<never, never>>,
    'safety-training': RouteRecordInfo<'safety-training', '/safety/training', Record<never, never>, Record<never, never>>,
  }
}
